spring:
  datasource:
    url: jdbc:mysql://39.98.113.163:3306/cart?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: ^je3X=2$/5TV
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    开启驼峰映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: support
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://39.98.113.163:2181
  scan:
    base-packages: com.zimingsir.cart.dubbo
  consumer:
    timeout: 3000