spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cart?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 5557773sql
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    开启驼峰映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl